# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-pulse-relay" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "438cf6d69afa71de60f2f4877b4454befbc82f84bd4abb69b26d2196fe987b2c"
      url "https://github.com/biokraft/claude-pulse/releases/download/v1.0.0/claude-pulse-relay_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d23659fa08daa13c4456bd6c9f933dff9089593645fa16c4905ad306667e195"
      url "https://github.com/biokraft/claude-pulse/releases/download/v1.0.0/claude-pulse-relay_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2dcc16d8a916227d1ad364ad72c47242eeb295332f049351b120c5d19fc3c023"
      url "https://github.com/biokraft/claude-pulse/releases/download/v1.0.0/claude-pulse-relay_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a79ac0e4cbbd53b8d9fa4466155abc85e8b06f6b21e934380c4fc8c135ba8614"
      url "https://github.com/biokraft/claude-pulse/releases/download/v1.0.0/claude-pulse-relay_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-pulse-relay"
  desc "Feeds the Claude Pulse Garmin watch app with your Claude Code usage"
  homepage "https://github.com/biokraft/claude-pulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-pulse-relay"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-pulse-relay"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Start the relay and pair your watch:
      claude-pulse-relay

    To run it in the background across reboots:
      claude-pulse-relay service install
  EOS
end
