# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-pulse-relay" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "042d98195ef15065f4610e30472aac11c59a3b79f9a2db8da46f9c392b74f4f8"
      url "https://github.com/biokraft/claude-pulse/releases/download/v#{version}/claude-pulse-relay_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7fb595e7500898ad07eff0399ccf746418f8218233444c6600fb7ac3bffa6182"
      url "https://github.com/biokraft/claude-pulse/releases/download/v#{version}/claude-pulse-relay_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "880c68c8edff01f80556f91ae3033b1b3ddfb235f724cb61ac2d253a4d0456b6"
      url "https://github.com/biokraft/claude-pulse/releases/download/v#{version}/claude-pulse-relay_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "46107d2b6d5a3bcf99f11b7cfb019f393df257867d7dd461c5325d03b5bfce7c"
      url "https://github.com/biokraft/claude-pulse/releases/download/v#{version}/claude-pulse-relay_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-pulse-relay"
  desc "Feeds the Claude Pulse Garmin watch app with your Claude Code usage"
  homepage "https://github.com/biokraft/claude-pulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-pulse-relay"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-pulse-relay"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Start the relay and pair your watch:
      claude-pulse-relay

    To run it in the background across reboots:
      claude-pulse-relay service install
  EOS
end
