# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-pulse-relay" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "d4fdc9f55319450ca6135762cdada8bb7b20a1dd6174686f9214790bdfbc9591"
      url "https://github.com/biokraft/claude-pulse/releases/download/v#{version}/claude-pulse-relay_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfc058171b6fc9e954424851704a1b7059535de6592bf3e59f8d196c387ddff1"
      url "https://github.com/biokraft/claude-pulse/releases/download/v#{version}/claude-pulse-relay_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95224d54937ad0dbf8fe78b0699f7e308ab7689e03ef31b88fca23a0ef51605b"
      url "https://github.com/biokraft/claude-pulse/releases/download/v#{version}/claude-pulse-relay_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2520ed49ef285cdfe822e58ebe66b6eea7f0dab0ecd0ce467e69ca50e375e48b"
      url "https://github.com/biokraft/claude-pulse/releases/download/v#{version}/claude-pulse-relay_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-pulse-relay"
  desc "Feeds the Claude Pulse Garmin watch app with your Claude Code usage"
  homepage "https://github.com/biokraft/claude-pulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-pulse-relay"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-pulse-relay"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Start the relay and pair your watch:
      claude-pulse-relay

    To run it in the background across reboots:
      claude-pulse-relay service install
  EOS
end
